# Generated by Django 4.1 on 2022-11-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0007_user_delete_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registration.user",
                    ),
                ),
                ("comts", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                ("post1", models.ImageField(upload_to="Images/")),
                ("like", models.IntegerField()),
            ],
            options={"verbose_name_plural": "All Post",},
        ),
    ]
