# Generated by Django 4.1 on 2022-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
