# Generated by Django 4.1 on 2022-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("gender", models.BooleanField()),
                ("age", models.IntegerField()),
                ("phone_number", models.CharField(max_length=10)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
