# Generated by Django 4.1 on 2022-10-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="gender",),
    ]
