# Generated by Django 4.1 on 2022-10-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="gender",
            field=models.CharField(
                choices=[("0", "female"), ("1", "male")], default="0", max_length=20
            ),
        ),
    ]
