# Generated by Django 4.1 on 2022-11-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_reg_gender"),
    ]

    operations = [
        migrations.RenameModel(old_name="reg", new_name="userInfo",),
        migrations.AlterModelOptions(
            name="userinfo", options={"ordering": ("username",)},
        ),
    ]
